live_config_reload = true

[colors.primary]
background = "0x414141"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"
startup_mode = "Windowed"

[font]
size = 16.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001"
key = "A"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002"
key = "B"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0004"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0007"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\b"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000B"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u000F"
key = "O"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0010"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0012"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0014"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B."
key = "Period"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B,"
key = "Comma"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "buttonless"

[window.padding]
x = 5
y = 5
