#!/bin/sh
# Set up Dotfiles

# Install Homebrew if needed
if ! type "brew" > /dev/null; then
    HOMEBREW_URL=https://raw.githubusercontent.com/Homebrew
    /bin/bash -c "$(curl -fsSL $HOMEBREW_URL/install/HEAD/install.sh)"
fi

 # Install brew dependencies
while read p; do
  brew install "$p"
done <~/.dotfiles/requirements/brew-reqs.txt

# Install cask dependencies
while read p; do
  brew install cask "$p"
done <~/.dotfiles/requirements/cask-reqs.txt

# Install Oh My Zsh
wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh

# Install Oh My Zsh Plugins
while read plugin; do
  gh_path=$(echo $plugin | cut -d ' ' -f 1)
  dst_path=$(echo $plugin | cut -d ' ' -f 2)
  git clone --depth=1 https://github.com/$gh_path ~/.oh-my-zsh/custom/plugins/$dst_path
done <~/.dotfiles/requirements/zsh-plugins.txt

# Install Powerlevel10k
git clone --depth=1 \
    https://github.com/romkatv/powerlevel10k.git \
    ~/.oh-my-zsh/custom/plugins/powerlevel10k

# Install FZF
brew install fzf && \
    $(brew --prefix)/opt/fzf/install

# Install Espanso
brew tap federico-terzi/espanso
brew install espanso
espanso register

# Install Fonts
brew tap homebrew/cask-fonts
brew install --cask font-hack-nerd-font

# Use ZSH by default
chsh -s $(which zsh)
