# Brew Dependencies

# Taps

tap "federico-terzi/espanso"
tap "homebrew/cask-fonts"

# Editor
brew "neovim"
brew "bat"
brew "trash"

# Navigation
brew "vifm"
brew "tree"

# Search and filter
brew "fzf"
brew "ripgrep"
brew "peco"
brew "tig"
brew "fd"
brew "jq"

# Common Tools
brew "wget"
brew "htop"
brew "speedtest-cli"
brew "thefuck"
brew "mint"
brew "cookiecutter"

# Image Tools
brew "imagemagick"
brew "gifsicle"
brew "ffmpeg"

# Python
brew "pyenv"
brew "virtualenv"
brew "pyenv-virtualenv"
brew "virtualenvwrapper"
brew "pyenv-virtualenvwrapper"

# `brew install --cask`
cask "maccy"
cask "qlmarkdown"
cask "qlmarkdown"
cask "rectangle"
cask "alacritty"
cask "macdown"
cask "alt-tab"
cask "docker"
cask "caffeine"
cask "logi-options-plus"
cask "postman"
cask "google-chrome"
cask "calibre"
cask "quik"
cask "folx"
cask "discord"
cask "fliqlo"
cask "vlc"
brew "espanso"

#cask "font-hack-nerd-font"
