#!/bin/sh
# Dotfiles Install Script
# {{{ Parameters:
# - none: install everything
# - BREW: install some brew dependencies
# - NVIM: set up `dein` and ini file
# - TMUX: set up tmuxrc file
# - GIT: set up git default config
# - HTOP: set up default htop file
# - OHMYZSH: install oh-my-zsh
# - PLUGINS: install oh my zsh req plugins
# - POWERLEVEL: install powerlevel 10k theme
# - FZF: install and set up fzf
# - JQ: install and set up jq utils and functions
# - RANGER: install and set up the Ranger terminal file manager
# - YABAI: install & set up Yabai tiling window manager
# - ALACRITTY: install & set up the alacritty terminal emulator
# - ESPANSO: set up the espanso daemon
# - ZSH: setup zsh as default shell
# }}}

# {{{ Initial Definitions

# Load script utils
source ~/.dotfiles/scripts/utils

# Define helpful variables
OH_MY_ZSH_DIR=$HOME/.oh-my-zsh
PLUGIN_DIR=$OH_MY_ZSH_DIR/custom/plugins
THEMES_DIR=$OH_MY_ZSH_DIR/custom/themes
GH_URL=https://github.com

[[ $# -eq 0 ]] && log_info ">>> No arguments supplied: Performing full instalation <<<"

# }}}

# {{{ Install Brew Dependencies

if [[ "$*" == *BREW* ]] || [[ $# -eq 0 ]]; then
    log_info ">>> BREW: Installing dependencies <<<"
    # Update brew
    brew update
    # Install brew dependencies
    while read p; do
      brew install "$p"
    done <~/.dotfiles/requirements/brew-reqs.txt
    # Install cask dependencies
    while read p; do
      brew install cask "$p"
    done <~/.dotfiles/requirements/cask-reqs.txt
fi

# }}}

# {{{ Set up Neovim

if [[ "$*" == *NVIM* ]] || [[ $# -eq 0 ]]; then
    safe_ln ~/.dotfiles/nvim ~/.config/nvim
    log_success ">>> NVIM: Success <<<"
fi

# }}}

# {{{ Set up TMUX

if [[ "$*" == *TMUX* ]] || [[ $# -eq 0 ]]; then
    safe_ln ~/.dotfiles/tmux.conf ~/.tmux.conf
    log_success ">>> TMUX: Success <<<"
fi

# }}}

# {{{ Set up Git

if [[ "$*" == *GIT* ]] || [[ $# -eq 0 ]]; then
    safe_ln ~/.dotfiles/git-template/gitconfig.global ~/.gitconfig
    log_success ">>> GIT: Success <<<"
fi

# }}}

# {{{ Set up htop

if [[ "$*" == *HTOP* ]] || [[ $# -eq 0 ]]; then
    safe_ln ~/.dotfiles/htop/htoprc ~/.config/htop/htoprc
    log_success ">>> HTOP: Success <<<"
fi

# }}}

# {{{ Set up Zsh

if [[ "$*" == *OHMYZSH* ]] || [[ $# -eq 0 ]]; then
    wget $GH_URL/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
    safe_ln ~/.dotfiles/zshrc ~/.zshrc
    log_success ">>> ZSH: Success <<<"
fi

if [[ "$*" == *PLUGINS* ]] || [[ $# -eq 0 ]]; then
    while read plugin; do
      gh_path=$(echo $plugin | cut -d ' ' -f 1)
      dst_path=$(echo $plugin | cut -d ' ' -f 2)
      git clone --depth=1 $GH_URL/$gh_path $PLUGIN_DIR/$dst_path
    done <~/.dotfiles/requirements/zsh-plugins.txt
    log_success ">>> ZSH: Plugins: Success  <<<"
fi

if [[ "$*" == *POWERLEVEL* ]] || [[ $# -eq 0 ]]; then
    git clone --depth=1 \
        $GH_URL/romkatv/powerlevel10k.git \
        $THEMES_DIR/powerlevel10k
    log_success ">>> ZSH: PowerLevel10K: Success <<<"
fi

# }}}

# {{{ Set up Fzf

if [[ "$*" == *FZF* ]] || [[ $# -eq 0 ]]; then
    brew install fzf
    $(brew --prefix)/opt/fzf/install
    log_success ">>> FZF: Success <<<"
fi

# }}}

# {{{ Set up jq

if [[ "$*" == *JQ* ]] || [[ $# -eq 0 ]]; then
    brew install jq
    ln -s ~/.dotfiles/jq ~/.jq
    log_success ">>> JQ: Success <<<"
fi

# }}}


# {{{ Set up Ranger

if [[ "$*" == *RANGER* ]] || [[ $# -eq 0 ]]; then
    # Install Ranger
    brew install ranger

    # Install config file
    mkdir -p ~/.config/ranger
    safe_ln ~/.dotfiles/ranger ~/.config/ranger

    log_success ">>> Ranger: Success <<<"
fi

# }}}

# {{{ Set up Yabai

if [[ "$*" == *YABAI* ]] || [[ $# -eq 0 ]]; then
    # Install yabai & skhdrc
    brew install koekeishiya/formulae/yabai
    brew install koekeishiya/formulae/skhd

    # load yabai sa
    sudo yabai --load-sa

    # start all services
    brew services start yabai
    brew services start skhd

    # Setup config files
    safe_ln ~/.dotfiles/yabairc ~/.yabairc
    safe_ln ~/.dotfiles/skhdrc ~/.skhdrc

    log_success ">>> YABAI: Success <<<"
fi

# }}}

# {{{ Set up Alacritty

if [[ "$*" == *ALACRITTY* ]] || [[ $# -eq 0 ]]; then
    brew install alacritty
    safe_ln ~/.dotfiles/alacritty.yml ~/.alacritty.yml
    log_success ">>> ALACRITTY: Success <<<"
fi

# }}}

# {{{ Set up Espanso

if [[ "$*" == *ESPANSO* ]] || [[ $# -eq 0 ]]; then
    # Install
    brew tap federico-terzi/espanso
    brew install espanso
    espanso register
    # Setup rc
    ln -s ~/.dotfiles/espansorc ~/Library/Preferences/espanso/user/espansorc.yml
    # Reload changes
    espanso restart

    log_success ">>> Espanso: Success <<<"
fi

# }}}

# {{{ Set up Zsh as default shell

if [[ "$*" == *ZSH* ]] || [[ $# -eq 0 ]]; then
    chsh -s $(which zsh)
    log_success ">>> ZSH is now the default shell <<<"
fi

# }}}
