#!/bin/sh
# Set up macOS default preferences
# Inspired by:
# https://gist.github.com/tylerwalts/9375263
# https://gist.github.com/bradp/bea76b16d3325f5c47d4

set -euo pipefail

# Color definitions
black='\033[0;30m'
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
purple='\033[0;35m'
cyan='\033[0;36m'
white='\033[0;37m'

# Log utils
function log_info() { echo "${cyan}$@${white}"; }
function log_success() { echo "${green}$@${white}"; }

# Menu bar
defaults write NSGlobalDomain _HIHideMenuBar -bool true         # Enable autohide

# Finder
defaults write com.apple.finder _FXShowPosixPathInTitle -bool YES               # Show file path
defaults write com.apple.finder ShowStatusBar -bool true                        # Show status bar
defaults wirte com.apple.finder ShowExternalHardDrivesOnDesktop -bool false     # Don't show stuff in my desktop
defaults write org.m0k.transmission UseIncompleteDownloadFolder -bool true      # Use folder for incomplete downloads
defaults write org.m0k.transmission IncompleteDownloadFolder -string "${HOME}/Downloads/Incomplete"

# Dock
defaults write com.apple.dock autohide -bool true               # Enable autohide
defaults write com.apple.dock autohide-delay -int 0             # Disable autohide delay
defaults write com.apple.dock static-only -bool true            # Show only active apps
defaults write com.apple.dock tilesize -integer 24              # Set normal size
defaults write com.apple.dock largesize -int 128                # Set magnified size
defaults write com.apple.dock mru-spaces -bool false            # Disable auto arrangement

# Screenshots
defaults write com.apple.screencapture location -string "${HOME}/Documents/Screenshots" # Change default location
defaults write com.apple.screencapture type -string "png"                               # Change default format

# Automatically illuminate built-in MacBook keyboard in low light
defaults write com.apple.BezelServices kDim -bool true

# Increase sound quality for Bluetooth headphones/headsets
defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

# Hot corners
defaults write com.apple.dock wvous-br-corner -int 5            # Bottom right → Start screen saver
defaults write com.apple.dock wvous-br-modifier -int 0          # Bottom right modifier → None

# Restart affected apps
killall Dock
killall Finder

# Show success
log_success ">>> Finished macOS setup successfully! <<<"
