#!/bin/sh
# Docker Minimal Setup
# Ever exec'd into a docker image just to find
# that you don't have access to your freaking tools?
# Well that ends now, with this spectacular (and probably slow and inefficient)
# script to copy the minimal local config to Docker! Yeah!
# FIXME: This is probably going to break with different base images, but yeah

docker cp ~/.config/minimal/bashrc $@:/etc/bash.bashrc
docker cp ~/.config/minimal/vimrc $@:/etc/vim/vimrc
