#!/bin/sh
# Set up macOS defaults

# Menu bar
defaults write NSGlobalDomain _HIHideMenuBar -bool false                 # Enable autohide
defaults write com.apple.menuextra.battery ShowPercent -bool true       # Show battery percentage
defaults write com.apple.controlcenter BatteryShowPercentage -bool true

# Finder
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true              # Show file path
defaults write com.apple.finder ShowStatusBar -bool true                        # Show status bar
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool false     # Don't show stuff in my desktop

# Dock
defaults write com.apple.dock autohide -bool true               # Enable autohide
defaults write com.apple.dock autohide-delay -int 0             # Disable autohide delay
defaults write com.apple.dock static-only -bool true            # Show only active apps
defaults write com.apple.dock tilesize -integer 24              # Set normal size
defaults write com.apple.dock largesize -int 128                # Set magnified size
defaults write com.apple.dock mru-spaces -bool false            # Disable auto arrangement

# Window Manager
defaults write com.apple.WindowManager EnableStandardClickToShowDesktop 0
defaults write -g NSWindowShouldDragOnGesture YES   # Allow CMD+Ctrl to move window

# Sound Quality
defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

# Screenshots
mkdir -p ~/Documents/Screenshots
defaults write com.apple.screencapture location ~/Documents/Screenshots
