#!/bin/sh
# Raspberry Pi / Minimal Server Setup
# Run after cloning this branch (see .github/README.md).

set -e

log() { printf '\033[0;36m%s\033[0m\n' "$1"; }

log "Installing packages via apt..."
sudo apt update
sudo apt install -y zsh git curl fzf bat neovim

log "Installing Oh My Zsh..."
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git "$HOME/.oh-my-zsh"
else
    log "Oh My Zsh already installed, skipping"
fi

ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"

log "Installing zsh-autosuggestions and zsh-syntax-highlighting..."
[ -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ] || \
    git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
[ -d "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" ] || \
    git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"

log "Switching default shell to zsh..."
chsh -s "$(which zsh)"

log "Set your git identity with: git config --global user.name/user.email"
log "Done! Restart your shell or run: exec zsh"
