#!/bin/sh
# Set up Dotfiles

# Install Homebrew if needed
if ! type "brew" > /dev/null; then
    HOMEBREW_URL=https://raw.githubusercontent.com/Homebrew
    /bin/bash -c "$(curl -fsSL $HOMEBREW_URL/install/HEAD/install.sh)"
fi

# Install brew dependencies
brew bundle --file=~/.dotfiles/requirements/Brewfile

# Install Oh My Zsh
wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh

# Install FZF
$(brew --prefix)/opt/fzf/install

# Use ZSH by default
chsh -s $(which zsh)
